// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPo-52pPAGQTdhAXIRlK9khzrRFrN5v_k',
    appId: '1:419525370744:web:fa953ca0362316d23d5e8d',
    messagingSenderId: '419525370744',
    projectId: 'sandra-foods-app',
    authDomain: 'sandra-foods-app.firebaseapp.com',
    databaseURL: 'https://sandra-foods-app-default-rtdb.firebaseio.com',
    storageBucket: 'sandra-foods-app.appspot.com',
    measurementId: 'G-VZF6T8BE8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6P_gmWlasiTZMwby6wc65n-AX8qKraV4',
    appId: '1:419525370744:android:1e5d7037af5b1c0d3d5e8d',
    messagingSenderId: '419525370744',
    projectId: 'sandra-foods-app',
    databaseURL: 'https://sandra-foods-app-default-rtdb.firebaseio.com',
    storageBucket: 'sandra-foods-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbxVlBej1qmaepwvnGE5FPoDEiKl2ATgI',
    appId: '1:419525370744:ios:fa213f042587255f3d5e8d',
    messagingSenderId: '419525370744',
    projectId: 'sandra-foods-app',
    databaseURL: 'https://sandra-foods-app-default-rtdb.firebaseio.com',
    storageBucket: 'sandra-foods-app.appspot.com',
    iosClientId: '419525370744-u832dbdk6gig5inseua8680kf3dc85ni.apps.googleusercontent.com',
    iosBundleId: 'com.ssoft.sandraFoodsApp',
  );
}
